# Generated by Django 5.2.7 on 2026-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='from-blue-400 to-purple-500', help_text='Tailwind gradient classes', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🙏', help_text='Emoji icon', max_length=10),
        ),
    ]
