# Generated by Django 5.2.7 on 2026-02-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_color_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='products',
        ),
        migrations.CreateModel(
            name='BundleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bundles/')),
                ('order', models.IntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.bundle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.bundle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
