# Generated by Django 5.2.7 on 2026-02-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productgrid_product_product_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
