# Generated by Django 5.2.7 on 2026-02-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='BundleItem',
        ),
    ]
