# Generated by Django 5.2.7 on 2026-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_order_delivery_address_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/'),
        ),
        migrations.DeleteModel(
            name='BundleImage',
        ),
    ]
