# Generated by Django 5.2.7 on 2026-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_bundleimage_remove_bundle_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='scrapsubmission',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapsubmission',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='from-blue-400 to-purple-500', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🙏', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('bank', 'Bank Transfer')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapsubmission',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
